- jrxml_reports/custom_reports/sqp_Internal_move_form.jrxml
- Delete PO Footer Band
- Add Blank Page Footer Band
- Add Last Page Footer Band with contents copied from the previous PO Footer Band
> Report#3050 moveline overflowed

- jrxml_reports/custom_reports/sqp_mo_material_use_summary.jrxml
- expand the product code field on the form
> Support#3106 product code does fit on MO Usage Summary (SQP)

- jrxml_reports/custom_reports.xml
- Comment out "Ship Panel Form (Merged)"
> Bug#3074 Disable Merged DO printing

- jrxml_reports/custom_reports/sqp_Internal_move_form.jrxml
- Adjust the internal move form to show Note in the page footer area
> Bug#3112 Retreive additional remark to show on Internal Move Form

- jrxml_reports/custom_reports/sqp_Internal_move_form.jrxml
- Change PDF font name to Garuda.ttf
- Change PDF Encoding to Idenity-H (Unicode with horizontal writing)
> Bug#3112-R2 Internal note not displaying Thai characters

- ext_amount_to_word/all_docs.py
- ext_amount_to_word/all_docs_view.xml
- ext_amount_to_word/amount_to_text_th.py
> Bug#3113 Amount to Text part 2

- ext_account_invoice_merge/__init__.py
- ext_account_invoice_merge/__openerp__.py
- ext_account_invoice_merge/wizard/__init__.py
- ext_account_invoice_merge/wizard/invoice_merge.py
- Inherit invoice_merge and then raise exception when hitting the customer invoices
> Support#3141 Disable Invoice Merge feature on Customer Invoices

- ext_purchase/purchase_requisition.py
- Make the warehouse field a required field
> Support#3205

- ext_purchase/__openerp__.py
- ext_purchase/purchase.py
- ext_purchase/purchase_view.xml
- ext_stock/__openerp__.py
- ext_stock/stock.py
- ext_stock/stock_view.xml
- Add Customer Name field in PO header
- Add Customer Name field in Internal Move header
> Feature#3098

- amount_to_word_ext_thai_wht/all_docs.py
> Support#3291 incorrect amount_to_text_th/en when tax withholding applied

- sqp_production_report/sqp_report_production_daily.jrxml
- Change the where clause to filter audittrial log based on new
date/time criteria
> Feature#3276 Change Daily report query condition

- sqp_production_report/sqp_report_production_daily.jrxml
- rewrite sql query for the report
> Feature#3276 revision 2

- sqp_production_report/sqp_report_production_daily.jrxml
- Add customer name as new column into Production Daily Report
> Change Request#3357

- jrxml_reports/custom_reports/sqp_supply_list_form.jrxml
list form (SQP)  
- Set Stretch with Overflow to true for both fields.
> Support#3378 Customer and Ref Project Name fields overflowed on Supply

- jrxml_reports/custom_reports/sqp_super_mo_form.jrxml
- jrxml_reports/custom_reports/sqp_super_mo_form_2.jrxml
- Split a line5 field into PIR and PU and some logics applied
> Report#3362 Revise MO form

- rml_reports/purchase/request_quotation.rml
- Edit Request for Quotation form 'QTY' to display only two decimal digit
> Support#3459

- ext_stock_balance_reorder/product.py
พี่หนุ่ยตรวจโคดให้หน่อยครับ
เวลาการเทสทุกกรณีของทั้ง 2 โคด(โคดเก่า และ โคดใหม่) ไม่ต่างกัน ที่ต่างกันคือโคดกระชับกว่า
> Bug reorder

- ext_stock_balance_reorder/product.py
> [ENH] modify method _search_product_reorder

- boi/__init__.py
- boi/__openerp__.py
- boi/boi.py
- boi/boi_view.xml
- bom_move/__init__.py
- bom_move/mrp.py
- bom_move/report_view/__init__.py
- bom_move/report_view/bom_move_report.py
- bom_move/report_view/bom_move_report_view.xml
P'nuii success my code, please review
> Enh pod bom move add bom move line and cancel bom move

- boi/__init__.py
- boi/__openerp__.py
- boi/boi.py
- boi/boi_view.xml
> [ADD] add boi

- bom_move/mrp.py
> [ENH] enh order_qty

- bom_move/report/bom_move_pdf.jrxml
- bom_move/report/bom_move_xls.jrxml
P'nuii I modfy bom move form, please commit and check on sqp web
> [ENH] modify bom move form

- bom_move/mrp.py
- bom_move/report/bom_move_pdf.jrxml
- bom_move/report/bom_move_xls.jrxml
- bom_move/stock.py
> modify document number of backorder of is bm from do 

- boi/__init__.py
- boi/__openerp__.py
- boi/account_invoice.py
- boi/account_invoice_view.xml
- boi/boi.py
- boi/boi_view.xml
- boi/mrp.py
- boi/procurement.py
- boi/product.py
- boi/product_rapid_create.py
- boi/product_rapid_create_view.xml
- boi/product_view.xml
- boi/purchase.py
- boi/purchase_requisition.py
- boi/purchase_requisition_view.xml
- boi/purchase_view.xml
- boi/sale.py
- boi/sale_line_invoice.py
- boi/sale_view.xml
- boi/stock.py
- boi/stock_invoice_onshipping.py
- boi/stock_partial_picking.py
- boi/stock_view.xml
- bom_move/mrp.py
- bom_move/stock_view.xml
> Enh pod bom move 

- boi/__init__.py
- boi/__openerp__.py
- boi/account_invoice.py
- boi/account_invoice_view.xml
- boi/boi.py
- boi/boi_view.xml
- boi/mrp.py
- boi/procurement.py
- boi/product.py
- boi/product_rapid_create.py
- boi/product_rapid_create_view.xml
- boi/product_view.xml
- boi/purchase.py
- boi/purchase_requisition.py
- boi/purchase_requisition_view.xml
- boi/purchase_view.xml
- boi/sale.py
- boi/sale_line_invoice.py
- boi/sale_view.xml
- boi/stock.py
- boi/stock_invoice_onshipping.py
- boi/stock_partial_picking.py
- boi/stock_view.xml
> Enh pod boi edit boi 1

- bom_move/__openerp__.py
- bom_move/report/bom_move_pdf.jrxml
- bom_move/report/bom_move_xls.jrxml
- bom_move/security/ir.model.access.csv
- bom_move/stock_view.xml
> [ENH] enh bom_move

- jrxml_reports/custom_reports/sqp_tax_invoice.jrxml
- stock_delivery_line_check/wizard/stock_partial_move.py
> [BUG] bug sdlc and change property number size rp.

- sqp-addons/boi/model/account_invoice.py
- sqp-addons/boi/model/mrp.py
- sqp-addons/boi/model/purchase_requisition.py
- sqp-addons/boi/model/sale.py
- sqp-addons/boi/model/stock.py
- sqp-addons/boi/model/stock_invoice_onshipping.py
- sqp-addons/bom_move/stock.py
- sqp-addons/jrxml_reports/custom_reports/sqp_super_mo_form.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_super_mo_form_2.jrxml
P'Nuii, please review and merge my code
> boi, bom move, report

- sqp-addons/boi/model/stock_partial_picking.py
P'Nuii please review and merge
> [BUG] bug 8

- sqp-addons/boi/model/sale.py
> [BUG] bug constraint

- sqp-addons/boi/model/sale.py
> [BUG] bug constraints

- sqp-addons/bom_move/stock.py
@kittiu 
please check for order by product in stock_move of bom move page
> order by product in stock move

- sqp-addons/bom_move/product_view.xml
> [ADD] add mo_out in product when view product

- sqp-addons/jrxml_reports/custom_reports/sqp_shipment_panel_form.jrxml
> Shipment Panel Report: Sort By Sequence

- sqp-addons/ext_mrp/__openerp__.py
- sqp-addons/ext_mrp/mrp_view.xml
- sqp-addons/ext_mrp/security/ext_mrp_security.xml
P'Nuii please review and merge
> [ADD] add group for cancel production

- sqp-addons/bom_move/stock_location_product.py
- sqp-addons/ext_stock_balance_reorder/product.py
- sqp-addons/ext_stock_balance_reorder/product_view.xml
> [IMP] add field sqp_outgoing_qty, sqp_virtual_available, sqp_qty_reorder

- sqp-addons/ext_stock_balance_reorder/product.py
- sqp-addons/ext_stock_balance_reorder/product_view.xml
> [IMP] add sqp_qty_mo_resv

- sqp-addons/bom_move/product_view.xml
- sqp-addons/ext_stock_balance_reorder/product.py
- sqp-addons/ext_stock_balance_reorder/product_view.xml
> [IMP] add SPS Incoming and adjust state

- sqp-addons/boi/model/account_invoice.py
- sqp-addons/boi/report/boi_report.py
- sqp-addons/boi/view/account_invoice_view.xml
> Add boi add boi picking ids in account invoice

- sqp-addons/product_stock_balance/__init__.py
- sqp-addons/product_stock_balance/__openerp__.py
- sqp-addons/product_stock_balance/models/__init__.py
- sqp-addons/product_stock_balance/models/product_stock_balance.py
- sqp-addons/product_stock_balance/security/ir.model.access.csv
- sqp-addons/product_stock_balance/views/product_stock_balance_view.xml
- sqp-addons/product_stock_balance/wizards/__init__.py
- sqp-addons/product_stock_balance/wizards/product_stock_balance_wizard.py
- sqp-addons/product_stock_balance/wizards/product_stock_balance_wizard.xml
P'Nuii please review.
**Problem**
Move to menu stock balance and then click run report as below picture
Result will show follow category
> Add ttc product stock balance new module

- revised-addons/web_printscreen_zb/static/src/js/web_printscreen_export.js
P'Nuii Please check and merge krub.
> [BUG] Print pdf and excel not cover all case (case link path from parent view)

- sqp-addons/product_stock_balance/wizards/product_stock_balance_wizard.py
- sqp-addons/product_stock_balance/wizards/product_stock_balance_wizard.xml
P'Nuii please review krub.
ref issue >> http://128.199.123.133:10083/issues/869
> [IMP] Add Location on Stock Balance Wizard

- sqp-addons/jrxml_reports/custom_reports/sqp_creditnote.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_creditnote_copy.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_purchase_order.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_sale_order.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_sale_order_nodiscount_col.jrxml
change address 5 Form :
-Credit Note
-Credit Note (copy)
-Purchase Order
-Sale Order
-Sale Order No Discount
> [FIX] change address in Form

- sqp-addons/boi/model/mrp.py
เพิ่ม Rockwool ที่ Insulation ตามที่ลูกค้าต้องการ
> FIX - name_search()

- sqp-addons/jrxml_reports/custom_reports/sqp_sale_order.jrxml
Waiting user test before merge.
> [7.0][FIX] Quote / Sale Order (SQP) Form

- sqp-addons/ext_advance_and_additional_discount/__openerp__.py
- sqp-addons/ext_advance_and_additional_discount/account_invoice.py
- sqp-addons/ext_advance_and_additional_discount/account_invoice_view.xml
- sqp-addons/ext_advance_and_additional_discount/wizard/__init__.py
- sqp-addons/ext_advance_and_additional_discount/wizard/update_amount_deposit.py
- sqp-addons/ext_advance_and_additional_discount/wizard/update_amount_deposit_view.xml
> [ADD] ext_advance_and_additional_discount: Add update_deposit

- sqp-addons/jrxml_reports/custom_reports/sqp_creditnote.jrxml
- sqp-addons/jrxml_reports/custom_reports/sqp_creditnote_copy.jrxml
> Fix Credit Note Form

- sqp-addons/product_bom_template_continuous_line/report/sqp_qa_sampling_continuous.jrxml
> Revert "[FIX] Edit font size"

- sqp-addons/jrxml_reports/custom_reports/sqp_purchase_order.jrxml
แก้ไข รายงาน sqp_purchase_order เป็น version Rev.2
> [UPD] custom_report:sqp_purchase_order Rev.2

- sqp-addons/jrxml_reports/custom_reports/sqp_purchase_order.jrxml
> [FIX] sqp_purchase_order:Effective date

- sqp-addons/boi/model/constant.py
> [FIX] boi: report header detail

- sqp-addons/boi/model/account_invoice.py
ทำให้ระบบตรวจสอบ ว่า boi cert หมดอายุหรือไม่ ถ้าหมดจะไม่แสดง boi ใน seq
> [IMP] account_invoice: boi check date range
